<?php

namespace Weapon\Handgun;

/**
 * Class Pistol
 */
class Handgun extends \Weapon\Handgun
{

    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

}