<?php

namespace Weapon;

/**
 * Class Automatic
 * @package Weapon
 */
class Automatic extends \Weapon
{

    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

} 