<?php

namespace Weapon;

/**
 * Class Handgun
 * @package Weapon
 */
class Handgun extends \Weapon
{

    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

} 